name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
            matrix:
                python_version: ['3.9', '3.10', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: install packages
        run: make install
      - name: test
        run: make test